services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: 2026_TYP_Conference_Bookings_v1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zt.s.HqFUN39@F
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d typ"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./API
      target: production
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/typ
      JWT_SECRET: 06051255a67bd0442ccc2e31fb440ffa8648d96721d62230104cab144eac1272bb546396c03288aabdb3278f274b60e5b036b8681656d2ec4bfc531ab9a362e7
      NODE_ENV: production
      PORT: 4000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  web:
    build:
      context: ./web-app
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  postgres-data:
