import { Amenity, Room, Booking, User } from '../types';

export const AMENITIES: Amenity[] = [
  { id: 'a1', name: 'Projector', icon: 'videocam-outline', description: 'HD projector with HDMI' },
  { id: 'a2', name: 'Whiteboard', icon: 'easel-outline', description: 'Large magnetic whiteboard' },
  { id: 'a3', name: 'Video conferencing', icon: 'people-outline', description: 'Zoom/Teams ready' },
  { id: 'a4', name: 'TV screen', icon: 'tv-outline', description: '55" 4K display' },
  { id: 'a5', name: 'Conference phone', icon: 'call-outline', description: 'Speakerphone' },
  { id: 'a6', name: 'Coffee station', icon: 'cafe-outline', description: 'Nespresso + water' },
  { id: 'a7', name: 'Natural light', icon: 'sunny-outline', description: 'Floor-to-ceiling windows' },
  { id: 'a8', name: 'Standing desks', icon: 'desktop-outline', description: 'Adjustable height desks' },
];

export const ROOMS: Room[] = [
  {
    id: 'r1',
    name: 'Horizon Boardroom',
    description: 'Spacious corner suite with panoramic city views. Ideal for executive meetings and client presentations.',
    capacity: 16,
    status: 'AVAILABLE',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    amenities: [AMENITIES[0], AMENITIES[1], AMENITIES[2], AMENITIES[6]],
    floor: '12',
    location: 'North Wing',
    rating: 4.92,
    reviewCount: 128,
    isFavorite: true,
  },
  {
    id: 'r2',
    name: 'Studio Loft',
    description: 'Bright, open-plan room with industrial accents. Perfect for creative workshops and brainstorming.',
    capacity: 10,
    status: 'AVAILABLE',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
    amenities: [AMENITIES[1], AMENITIES[3], AMENITIES[6], AMENITIES[7]],
    floor: '5',
    location: 'East Wing',
    rating: 4.87,
    reviewCount: 94,
  },
  {
    id: 'r3',
    name: 'Focus Pod A',
    description: 'Intimate glass-walled pod for 1:1s or small team syncs. Fully sound-isolated.',
    capacity: 4,
    status: 'AVAILABLE',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&q=80',
    amenities: [AMENITIES[3], AMENITIES[4]],
    floor: '3',
    location: 'Core',
    rating: 4.95,
    reviewCount: 210,
  },
  {
    id: 'r4',
    name: 'Summit Theatre',
    description: 'Tiered seating and cinema-grade AV. Built for all-hands, training, and product launches.',
    capacity: 40,
    status: 'AVAILABLE',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1431540015161-0bf268a2e4ca?w=800&q=80',
    amenities: [AMENITIES[0], AMENITIES[2], AMENITIES[3], AMENITIES[5]],
    floor: 'B1',
    location: 'Auditorium',
    rating: 4.78,
    reviewCount: 67,
  },
  {
    id: 'r5',
    name: 'Garden Meeting',
    description: 'Ground-floor room opening onto the courtyard. Natural light and calm outdoor access.',
    capacity: 8,
    status: 'AVAILABLE',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80',
    amenities: [AMENITIES[1], AMENITIES[6], AMENITIES[5]],
    floor: 'G',
    location: 'Courtyard',
    rating: 4.89,
    reviewCount: 156,
    isFavorite: true,
  },
];

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'Alex Rivera',
  email: 'alex.rivera@company.com',
  department: 'Operations',
  contactNumber: '+27 82 555 0192',
  role: 'CLERK',
  avatarUrl: 'https://i.pravatar.cc/150?u=alex',
};

export const MOCK_CLERK_QUEUE: Booking[] = [
  {
    id: 'b2',
    employeeId: 'u2',
    startAt: '2026-08-28T09:00:00Z',
    endAt: '2026-08-28T10:00:00Z',
    purpose: 'Q3 roadmap review with design leads',
    status: 'CONFIRMED',
    createdAt: '2026-08-27T09:00:00Z',
    rooms: [{ id: 'br2', roomId: 'r1', room: ROOMS[0] }],
    requestedAmenities: [AMENITIES[0], AMENITIES[2]],
  },
  {
    id: 'b3',
    employeeId: 'u3',
    startAt: '2026-08-28T11:30:00Z',
    endAt: '2026-08-28T12:30:00Z',
    purpose: 'Finance board briefing',
    status: 'PREPARING',
    createdAt: '2026-08-27T10:30:00Z',
    rooms: [{ id: 'br3', roomId: 'r4', room: ROOMS[3] }],
    requestedAmenities: [AMENITIES[1], AMENITIES[4]],
  },
  {
    id: 'b4',
    employeeId: 'u4',
    startAt: '2026-08-28T14:00:00Z',
    endAt: '2026-08-28T15:00:00Z',
    purpose: 'Customer onboarding demo',
    status: 'READY',
    createdAt: '2026-08-27T11:00:00Z',
    rooms: [{ id: 'br4', roomId: 'r5', room: ROOMS[4] }],
    requestedAmenities: [AMENITIES[3]],
  },
  {
    id: 'b5',
    employeeId: 'u5',
    startAt: '2026-08-28T16:30:00Z',
    endAt: '2026-08-28T17:30:00Z',
    purpose: 'Harbor team sync',
    status: 'COMPLETED',
    createdAt: '2026-08-27T12:00:00Z',
    rooms: [{ id: 'br5', roomId: 'r2', room: ROOMS[1] }],
    requestedAmenities: [AMENITIES[5]],
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    employeeId: 'u1',
    startAt: '2026-08-28T10:00:00Z',
    endAt: '2026-08-28T12:00:00Z',
    purpose: 'Q3 roadmap review with design leads',
    status: 'CONFIRMED',
    createdAt: '2026-08-25T09:12:00Z',
    rooms: [{ id: 'br1', roomId: 'r1', room: ROOMS[0] }],
    requestedAmenities: [AMENITIES[0], AMENITIES[2]],
  },
];
